apiVersion: v1
kind: Service
metadata:
  name: cqrs-service
  labels:
    app: cqrs-service
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: management
    port: 8558
    protocol: TCP
    targetPort: 8558
  - name: remoting
    port: 2552
    protocol: TCP
    targetPort: 2552
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cqrs-service
  clusterIP: None
  publishNotReadyAddresses: true