apiVersion: app.lightbend.com/v1alpha1
kind: AkkaCluster
metadata:
  name: cqrs-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cqrs-service
        actorSystemName: cqrs-service
    spec:
      containers:
      - name: main-write
        image: gcr.io/none-219021/akka-sample-cqrs-scala:1.8
        readinessProbe:
          httpGet:
            path: "/ready"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: "/alive"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        ports:
        - name: http
          containerPort: 8080
        - name: remoting
          containerPort: 2552
        - name: management
          containerPort: 8558
        env:
        - name: CONF_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: conf_env
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: http_port
        - name: CLUSTER_ROLE_ONE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: write-model
        - name: CASSANDRA_CONTACT_POINT_ONE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: cassandra-contact-point-one
